name = "entity-validator"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[env.production.vars]
BACKEND_API_URL = "https://entity-validator-backend-production-6962.up.railway.app"
ENVIRONMENT = "production"

[env.preview.vars]
BACKEND_API_URL = "https://entity-validator-backend-production-6962.up.railway.app"
ENVIRONMENT = "production"
